### PR TITLE
add optional flag to support custom username suffix

### PR DESCRIPTION
**Pull request by arnisoph**
There are some hacky parts where I haven't found a clean way for implementation. I guess we'd need to refactor some parts to make something like configurable claim mapping anyway..

### CODE REVIEW

**Comment by arnisoph** [comment]
@negz the use case is simply the fact that we have k8s clusters in several regions and each region holds a dedicated oidc provider. The username (email) is the same across all regions but the tokens are different. Thus the kubectl internal "username" that is as reference to define contexts need to be unique.

**Comment by arnisoph** [comment]
@negz any feedback? :)

**Comment by negz** [comment]
@arnoldbechtoldt Apologies for the very late response!

Given this is the internal username (i.e. basically a key in the `kubecfg` that I assume folks rarely think about) I wonder whether we can just enable this functionality you propose by default? Perhaps add a random suffix to all usernames, rather than having a configurable suffix?

**Comment by arnisoph** [comment]
I think a well-defined and reasonable suffix is better than a random string. And I rather not change the default behaviour since it leads to a *significant/breaking* change to the users that are already using kuberos, isn't it?

**Comment by negz** [comment]
> it leads to a significant/breaking change to the users that are already using kuberos, isn't it?

I don't _think_ it should. It would change the `name` key of each user, and the `user` key of the context that addresses those users. I believe that would only affect users if they were calling `kubectl --user someuser ...`, which I suspect would be a fairly niche/uncommmon use case.

**Comment by arnisoph** [comment]
But it duplicates the user object which messes the user's config up and thus confuses her/him. I'm talking about IT people in small to large organisations that aren't Kubernetes cracks yet. I'm working for these kind of orgs. Admins using kuberos will have to communicate to their users, that they need to download the kubectl file again, because the context (and user reference) has changed. Otherwise the new user object won't be referenced/used.
This leads to work for the admins (and users) without having any benefits. I doubt all orgs need that username suffix feature.

You know your community. I can live with your decisions as maintainer, but I'd have a problem updating my own code with the proposed change.

**Comment by jhohertz** [comment]
Just wanted to make note that I was about to make the same patch, for the same reasons. We have multiple k8s clusters, each with their own dex instance. With the existing CLI helper I am using, I added the ability to add a suffix, and we typically set that to the name of the cluster they're logging into. (As opposed to some random string).

If you were looking to have this "by default", I might suggest taking say, the hostname of the OIDC provider, massage that (IE: `s/./_/g`) and use the result as a suffix, encoding both the username and the provider into the name?

**Comment by arnisoph** [comment]
I've update the PR. @negz can we find some consens here? I'd like to stop maintaining a local fork. :)

**Comment by negz** [comment]
> Admins using kuberos will have to communicate to their users, that they need to download the kubectl file again, because the context (and user reference) has changed. Otherwise the new user object won't be referenced/used.

I empathise, but I'm afraid that I'd still prefer to require users redownload a kubeconfig file, as part of a breaking Kuberos change, than make the changes proposed by this PR as it stands today. I understand this is painful for users, but I'm not a fan of plumbing the username suffix throughout the codebase.

I would be happy to accept a PR that alleviated this issue by creating unique `kubeconfig` context names by default, be they random or derived from some other factor (perhaps the cluster name?).

**Pull request closed without merging**
